---
name: Catalyst-View-Mason
version: 0.07
author:
  - |-
    Andres Kievsky C<ank@cpan.org>
    Sebastian Riedel C<sri@cpan.org>
    Marcus Ramberg
abstract: Mason View Class
license: perl
requires:
  Catalyst: 5
  HTML::Mason: 0
provides:
  Catalyst::Helper::View::Mason:
    file: lib/Catalyst/Helper/View/Mason.pm
  Catalyst::View::Mason:
    file: lib/Catalyst/View/Mason.pm
    version: 0.07
generated_by: Module::Build version 0.2609
