---
abstract: 'Mason View Class'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Mason
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Catalyst::Helper::View::Mason:
    file: lib/Catalyst/Helper/View/Mason.pm
    version: 0.13
  Catalyst::View::Mason:
    file: lib/Catalyst/View/Mason.pm
    version: 0.18
requires:
  Catalyst: 5.50
  File::Spec: 0
  HTML::Mason: 0
  MRO::Compat: 0
  Scalar::Util: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-Mason/trunk/
version: 0.18
