# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-Mason
version:      0.03
version_from: lib/Catalyst/View/Mason.pm
installdirs:  site
requires:
    Catalyst:                      4.00
    HTML::Mason:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
